language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t visheshmadaan13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true visheshmadaan13/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-386875847391"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY