FROM node:alpine
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
CMD ["npm","start"]

# CLI for running container -> docker run -it -p 3000:3000 -v /home/node/app/node_modules -v $(pwd):/home/node/app visheshmadaan13/frontend


# We are specifying that the USER which will execute RUN, CMD, or ENTRYPOINT instructions will be the node user, as opposed to root (default).

# We are then creating a directory of /home/node/app prior to the WORKDIR instruction. This will prevent a permissions issue since WORKDIR by default will create a directory if it does not exist and set ownership to root.

# The inline chown commands will set ownership of the files you are copying from your local environment to the node user in the container.

# The end result will be that all files and directories in the project will no longer be owned by root and will instead be owned by the node user.